# Generated by Django 2.2.3 on 2019-10-02 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0002_addgroup_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groups',
            new_name='group_list',
        ),
        migrations.AlterField(
            model_name='addgroup',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
