# Generated by Django 2.2.3 on 2019-10-02 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0004_auto_20191002_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgroup',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=50, null=True), size=None),
        ),
    ]
