# Generated by Django 2.2.3 on 2019-10-02 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0007_auto_20191002_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
