# Generated by Django 2.2.3 on 2019-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0011_auto_20191002_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgroup',
            name='admin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.CharField(max_length=30),
        ),
    ]
