# Generated by Django 2.2.3 on 2019-10-03 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0012_auto_20191002_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField()),
                ('member', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None)),
            ],
        ),
    ]
