# Generated by Django 2.2.3 on 2019-10-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0013_grouprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprequest',
            old_name='member',
            new_name='members',
        ),
    ]
