# Generated by Django 2.2.3 on 2019-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0014_auto_20191003_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('recharge_on', models.DateTimeField()),
                ('plantype', models.CharField(max_length=30)),
                ('noofgroup', models.FloatField()),
            ],
        ),
    ]
