# Generated by Django 2.2.3 on 2019-10-17 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_user', '0015_groupplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=40)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000, null=True), size=None)),
                ('timestamp', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
            ],
        ),
    ]
